from app.modules.system.auth.models import Permission


def system_permissions() -> list[Permission]:
    return [
        Permission(id="perm-dashboard-view", code="dashboard:view", name="查看工作桌面"),
        Permission(id="perm-system-super-admin", code="system:super_admin", name="超级管理员"),
        Permission(id="perm-schedule-create", code="schedule:create", name="新增个人日程"),
        Permission(id="perm-announcement-create", code="announcement:create", name="发布公司公告"),
        Permission(
            id="perm-product-view",
            code="masterdata:product:view",
            name="查看商品资料",
        ),
        Permission(
            id="perm-product-edit",
            code="masterdata:product:edit",
            name="维护商品资料",
        ),
        Permission(
            id="perm-product-export",
            code="masterdata:product:export",
            name="导出商品资料",
        ),
        Permission(
            id="perm-customer-view",
            code="masterdata:customer:view",
            name="查看客户资料",
        ),
        Permission(
            id="perm-customer-edit",
            code="masterdata:customer:edit",
            name="维护客户资料",
        ),
        Permission(
            id="perm-customer-credit-view",
            code="masterdata:customer:credit:view",
            name="查看客户授信额度",
        ),
        Permission(
            id="perm-customer-credit-edit",
            code="masterdata:customer:credit:edit",
            name="维护客户信用信息",
        ),
        Permission(
            id="perm-customer-view-all",
            code="masterdata:customer:view_all",
            name="查看全部客户",
        ),
        Permission(
            id="perm-supplier-view",
            code="masterdata:supplier:view",
            name="查看供应商资料",
        ),
        Permission(
            id="perm-supplier-edit",
            code="masterdata:supplier:edit",
            name="维护供应商资料",
        ),
        Permission(
            id="perm-supplier-credit-view",
            code="masterdata:supplier:credit:view",
            name="查看供应商授信额度",
        ),
        Permission(
            id="perm-supplier-credit-edit",
            code="masterdata:supplier:credit:edit",
            name="维护供应商信用信息",
        ),
        Permission(
            id="perm-supplier-view-all",
            code="masterdata:supplier:view_all",
            name="查看全部供应商",
        ),
        Permission(
            id="perm-partner-view",
            code="masterdata:partner:view",
            name="查看合作伙伴",
        ),
        Permission(
            id="perm-partner-edit",
            code="masterdata:partner:edit",
            name="维护合作伙伴",
        ),
        Permission(
            id="perm-partner-view-all",
            code="masterdata:partner:view_all",
            name="查看全部合作伙伴",
        ),
        Permission(
            id="perm-document-party-view",
            code="masterdata:document_party:view",
            name="查看单证资料",
        ),
        Permission(
            id="perm-document-party-edit",
            code="masterdata:document_party:edit",
            name="维护单证资料",
        ),
        Permission(
            id="perm-document-party-view-all",
            code="masterdata:document_party:view_all",
            name="查看全部单证资料",
        ),
        Permission(
            id="perm-sample-request-view",
            code="sample:request:view",
            name="查看打样管理",
        ),
        Permission(
            id="perm-sample-request-edit",
            code="sample:request:edit",
            name="维护打样管理",
        ),
        Permission(
            id="perm-sample-request-view-all",
            code="sample:request:view_all",
            name="查看全部打样单",
        ),
        Permission(
            id="perm-sample-request-fee-edit",
            code="sample:request:fee:edit",
            name="维护打样费用",
        ),
        Permission(
            id="perm-sample-record-view",
            code="sample:record:view",
            name="查看样品登记",
        ),
        Permission(
            id="perm-sample-record-edit",
            code="sample:record:edit",
            name="维护样品登记",
        ),
        Permission(
            id="perm-sample-record-view-all",
            code="sample:record:view_all",
            name="查看全部样品",
        ),
        Permission(
            id="perm-sample-delivery-view",
            code="sample:delivery:view",
            name="查看寄样管理",
        ),
        Permission(
            id="perm-sample-delivery-edit",
            code="sample:delivery:edit",
            name="维护寄样管理",
        ),
        Permission(
            id="perm-sample-delivery-view-all",
            code="sample:delivery:view_all",
            name="查看全部寄样单",
        ),
        Permission(
            id="perm-sample-delivery-approve",
            code="sample:delivery:approve",
            name="审核寄样单",
        ),
        Permission(
            id="perm-sample-delivery-fee-view",
            code="sample:delivery:fee:view",
            name="查看寄样费用统计",
        ),
        Permission(
            id="perm-sales-quotation-view",
            code="sales:quotation:view",
            name="查看出口报价",
        ),
        Permission(
            id="perm-sales-quotation-edit",
            code="sales:quotation:edit",
            name="维护出口报价",
        ),
        Permission(
            id="perm-sales-quotation-view-all",
            code="sales:quotation:view_all",
            name="查看全部出口报价",
        ),
        Permission(
            id="perm-sales-quotation-approve",
            code="sales:quotation:approve",
            name="审批出口报价",
        ),
        Permission(
            id="perm-sales-quotation-export",
            code="sales:quotation:export",
            name="导出出口报价",
        ),
        Permission(id="perm-sales-contract-view", code="sales:contract:view", name="查看出口合同"),
        Permission(
            id="perm-sales-contract-edit",
            code="sales:contract:edit",
            name="维护出口合同",
        ),
        Permission(
            id="perm-sales-contract-view-all",
            code="sales:contract:view_all",
            name="查看全部出口合同",
        ),
        Permission(
            id="perm-sales-contract-approve",
            code="sales:contract:approve",
            name="审批出口合同",
        ),
        Permission(
            id="perm-sales-contract-export",
            code="sales:contract:export",
            name="导出出口合同",
        ),
        Permission(
            id="perm-sales-shipment-view",
            code="sales:shipment:view",
            name="查看出货明细",
        ),
        Permission(
            id="perm-sales-shipment-edit",
            code="sales:shipment:edit",
            name="维护出货明细",
        ),
        Permission(
            id="perm-sales-shipment-view-all",
            code="sales:shipment:view_all",
            name="查看全部出货明细",
        ),
        Permission(
            id="perm-sales-shipment-approve",
            code="sales:shipment:approve",
            name="审批出货明细",
        ),
        Permission(
            id="perm-purchase-inquiry-view",
            code="purchase:inquiry:view",
            name="查看采购询价",
        ),
        Permission(
            id="perm-purchase-inquiry-edit",
            code="purchase:inquiry:edit",
            name="维护采购询价",
        ),
        Permission(
            id="perm-purchase-inquiry-view-all",
            code="purchase:inquiry:view_all",
            name="查看全部采购询价",
        ),
        Permission(
            id="perm-purchase-inquiry-export",
            code="purchase:inquiry:export",
            name="导出采购询价模板",
        ),
        Permission(
            id="perm-purchase-contract-view",
            code="purchase:contract:view",
            name="查看采购合同",
        ),
        Permission(
            id="perm-purchase-contract-edit",
            code="purchase:contract:edit",
            name="维护采购合同",
        ),
        Permission(
            id="perm-purchase-contract-view-all",
            code="purchase:contract:view_all",
            name="查看全部采购合同",
        ),
        Permission(
            id="perm-purchase-contract-approve",
            code="purchase:contract:approve",
            name="审批采购合同",
        ),
        Permission(
            id="perm-purchase-invoice-notice-view",
            code="purchase:invoice_notice:view",
            name="查看开票通知",
        ),
        Permission(
            id="perm-purchase-invoice-notice-edit",
            code="purchase:invoice_notice:edit",
            name="维护开票通知",
        ),
        Permission(
            id="perm-purchase-invoice-notice-view-all",
            code="purchase:invoice_notice:view_all",
            name="查看全部开票通知",
        ),
        Permission(
            id="perm-purchase-invoice-notice-send",
            code="purchase:invoice_notice:send",
            name="发送开票通知",
        ),
        Permission(
            id="perm-purchase-followup-view",
            code="purchase:followup:view",
            name="查看采购跟单",
        ),
        Permission(
            id="perm-followup-template-view",
            code="followup:template:view",
            name="查看跟单模板",
        ),
        Permission(
            id="perm-followup-template-edit",
            code="followup:template:edit",
            name="维护跟单模板",
        ),
        Permission(
            id="perm-followup-plan-view",
            code="followup:plan:view",
            name="查看采购跟单计划",
        ),
        Permission(
            id="perm-followup-plan-edit",
            code="followup:plan:edit",
            name="维护采购跟单计划",
        ),
        Permission(
            id="perm-followup-plan-view-all",
            code="followup:plan:view_all",
            name="查看全部采购跟单计划",
        ),
        Permission(
            id="perm-quality-inspection-view",
            code="quality:inspection:view",
            name="查看 QC 查验",
        ),
        Permission(
            id="perm-quality-inspection-edit",
            code="quality:inspection:edit",
            name="维护 QC 查验",
        ),
        Permission(
            id="perm-quality-inspection-view-all",
            code="quality:inspection:view_all",
            name="查看全部 QC 查验",
        ),
        Permission(
            id="perm-warehouse-inbound-plan-view",
            code="warehouse:inbound_plan:view",
            name="查看入库计划",
        ),
        Permission(
            id="perm-warehouse-inbound-plan-edit",
            code="warehouse:inbound_plan:edit",
            name="维护入库计划",
        ),
        Permission(
            id="perm-warehouse-inbound-plan-view-all",
            code="warehouse:inbound_plan:view_all",
            name="查看全部入库计划",
        ),
        Permission(
            id="perm-warehouse-inbound-order-view",
            code="warehouse:inbound_order:view",
            name="查看货物入库",
        ),
        Permission(
            id="perm-warehouse-inbound-order-edit",
            code="warehouse:inbound_order:edit",
            name="维护货物入库",
        ),
        Permission(
            id="perm-warehouse-inbound-order-approve",
            code="warehouse:inbound_order:approve",
            name="审批货物入库",
        ),
        Permission(
            id="perm-warehouse-inbound-order-view-all",
            code="warehouse:inbound_order:view_all",
            name="查看全部货物入库",
        ),
        Permission(
            id="perm-warehouse-outbound-plan-view",
            code="warehouse:outbound_plan:view",
            name="查看出库计划",
        ),
        Permission(
            id="perm-warehouse-outbound-plan-edit",
            code="warehouse:outbound_plan:edit",
            name="维护出库计划",
        ),
        Permission(
            id="perm-warehouse-outbound-plan-view-all",
            code="warehouse:outbound_plan:view_all",
            name="查看全部出库计划",
        ),
        Permission(
            id="perm-warehouse-outbound-order-view",
            code="warehouse:outbound_order:view",
            name="查看货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-edit",
            code="warehouse:outbound_order:edit",
            name="维护货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-approve",
            code="warehouse:outbound_order:approve",
            name="审批货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-view-all",
            code="warehouse:outbound_order:view_all",
            name="查看全部货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-allow-negative",
            code="warehouse:outbound_order:allow_negative",
            name="授权负库存出库",
        ),
        Permission(id="perm-finance-view", code="finance:view", name="查看财务管理"),
        Permission(id="perm-reporting-view", code="reporting:view", name="查看经理查询"),
    ]
