from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.modules.system.auth.models import (
    Department,
    MenuItem,
    Permission,
    Role,
    RolePermission,
    User,
    UserRole,
)
from app.modules.system.auth.passwords import hash_password


async def seed_system_demo_data(session: AsyncSession) -> None:
    permissions = [
        Permission(id="perm-dashboard-view", code="dashboard:view", name="查看工作桌面"),
        Permission(id="perm-schedule-create", code="schedule:create", name="新增个人日程"),
        Permission(
            id="perm-product-view",
            code="masterdata:product:view",
            name="查看商品资料",
        ),
        Permission(
            id="perm-product-edit",
            code="masterdata:product:edit",
            name="维护商品资料",
        ),
        Permission(
            id="perm-product-export",
            code="masterdata:product:export",
            name="导出商品资料",
        ),
        Permission(
            id="perm-customer-view",
            code="masterdata:customer:view",
            name="查看客户资料",
        ),
        Permission(
            id="perm-customer-edit",
            code="masterdata:customer:edit",
            name="维护客户资料",
        ),
        Permission(
            id="perm-customer-credit-view",
            code="masterdata:customer:credit:view",
            name="查看客户授信额度",
        ),
        Permission(
            id="perm-customer-credit-edit",
            code="masterdata:customer:credit:edit",
            name="维护客户信用信息",
        ),
        Permission(
            id="perm-customer-view-all",
            code="masterdata:customer:view_all",
            name="查看全部客户",
        ),
        Permission(
            id="perm-supplier-view",
            code="masterdata:supplier:view",
            name="查看供应商资料",
        ),
        Permission(
            id="perm-supplier-edit",
            code="masterdata:supplier:edit",
            name="维护供应商资料",
        ),
        Permission(
            id="perm-supplier-credit-view",
            code="masterdata:supplier:credit:view",
            name="查看供应商授信额度",
        ),
        Permission(
            id="perm-supplier-credit-edit",
            code="masterdata:supplier:credit:edit",
            name="维护供应商信用信息",
        ),
        Permission(
            id="perm-supplier-view-all",
            code="masterdata:supplier:view_all",
            name="查看全部供应商",
        ),
        Permission(
            id="perm-partner-view",
            code="masterdata:partner:view",
            name="查看合作伙伴",
        ),
        Permission(
            id="perm-partner-edit",
            code="masterdata:partner:edit",
            name="维护合作伙伴",
        ),
        Permission(
            id="perm-partner-view-all",
            code="masterdata:partner:view_all",
            name="查看全部合作伙伴",
        ),
        Permission(
            id="perm-document-party-view",
            code="masterdata:document_party:view",
            name="查看单证资料",
        ),
        Permission(
            id="perm-document-party-edit",
            code="masterdata:document_party:edit",
            name="维护单证资料",
        ),
        Permission(
            id="perm-document-party-view-all",
            code="masterdata:document_party:view_all",
            name="查看全部单证资料",
        ),
        Permission(
            id="perm-sample-request-view",
            code="sample:request:view",
            name="查看打样管理",
        ),
        Permission(
            id="perm-sample-request-edit",
            code="sample:request:edit",
            name="维护打样管理",
        ),
        Permission(
            id="perm-sample-request-view-all",
            code="sample:request:view_all",
            name="查看全部打样单",
        ),
        Permission(
            id="perm-sample-request-fee-edit",
            code="sample:request:fee:edit",
            name="维护打样费用",
        ),
        Permission(
            id="perm-sample-record-view",
            code="sample:record:view",
            name="查看样品登记",
        ),
        Permission(
            id="perm-sample-record-edit",
            code="sample:record:edit",
            name="维护样品登记",
        ),
        Permission(
            id="perm-sample-record-view-all",
            code="sample:record:view_all",
            name="查看全部样品",
        ),
        Permission(
            id="perm-sample-delivery-view",
            code="sample:delivery:view",
            name="查看寄样管理",
        ),
        Permission(
            id="perm-sample-delivery-edit",
            code="sample:delivery:edit",
            name="维护寄样管理",
        ),
        Permission(
            id="perm-sample-delivery-view-all",
            code="sample:delivery:view_all",
            name="查看全部寄样单",
        ),
        Permission(
            id="perm-sample-delivery-approve",
            code="sample:delivery:approve",
            name="审核寄样单",
        ),
        Permission(
            id="perm-sample-delivery-fee-view",
            code="sample:delivery:fee:view",
            name="查看寄样费用统计",
        ),
        Permission(
            id="perm-sales-quotation-view",
            code="sales:quotation:view",
            name="查看出口报价",
        ),
        Permission(
            id="perm-sales-quotation-edit",
            code="sales:quotation:edit",
            name="维护出口报价",
        ),
        Permission(
            id="perm-sales-quotation-view-all",
            code="sales:quotation:view_all",
            name="查看全部出口报价",
        ),
        Permission(
            id="perm-sales-quotation-approve",
            code="sales:quotation:approve",
            name="审批出口报价",
        ),
        Permission(
            id="perm-sales-quotation-export",
            code="sales:quotation:export",
            name="导出出口报价",
        ),
        Permission(id="perm-sales-contract-view", code="sales:contract:view", name="查看出口合同"),
        Permission(
            id="perm-sales-contract-edit",
            code="sales:contract:edit",
            name="维护出口合同",
        ),
        Permission(
            id="perm-sales-contract-view-all",
            code="sales:contract:view_all",
            name="查看全部出口合同",
        ),
        Permission(
            id="perm-sales-contract-approve",
            code="sales:contract:approve",
            name="审批出口合同",
        ),
        Permission(
            id="perm-sales-contract-export",
            code="sales:contract:export",
            name="导出出口合同",
        ),
        Permission(
            id="perm-sales-shipment-view",
            code="sales:shipment:view",
            name="查看出货明细",
        ),
        Permission(
            id="perm-sales-shipment-edit",
            code="sales:shipment:edit",
            name="维护出货明细",
        ),
        Permission(
            id="perm-sales-shipment-view-all",
            code="sales:shipment:view_all",
            name="查看全部出货明细",
        ),
        Permission(
            id="perm-sales-shipment-approve",
            code="sales:shipment:approve",
            name="审批出货明细",
        ),
        Permission(
            id="perm-purchase-inquiry-view",
            code="purchase:inquiry:view",
            name="查看采购询价",
        ),
        Permission(
            id="perm-purchase-inquiry-edit",
            code="purchase:inquiry:edit",
            name="维护采购询价",
        ),
        Permission(
            id="perm-purchase-inquiry-view-all",
            code="purchase:inquiry:view_all",
            name="查看全部采购询价",
        ),
        Permission(
            id="perm-purchase-inquiry-export",
            code="purchase:inquiry:export",
            name="导出采购询价模板",
        ),
        Permission(
            id="perm-purchase-contract-view",
            code="purchase:contract:view",
            name="查看采购合同",
        ),
        Permission(
            id="perm-purchase-contract-edit",
            code="purchase:contract:edit",
            name="维护采购合同",
        ),
        Permission(
            id="perm-purchase-contract-view-all",
            code="purchase:contract:view_all",
            name="查看全部采购合同",
        ),
        Permission(
            id="perm-purchase-contract-approve",
            code="purchase:contract:approve",
            name="审批采购合同",
        ),
        Permission(
            id="perm-purchase-invoice-notice-view",
            code="purchase:invoice_notice:view",
            name="查看开票通知",
        ),
        Permission(
            id="perm-purchase-invoice-notice-edit",
            code="purchase:invoice_notice:edit",
            name="维护开票通知",
        ),
        Permission(
            id="perm-purchase-invoice-notice-view-all",
            code="purchase:invoice_notice:view_all",
            name="查看全部开票通知",
        ),
        Permission(
            id="perm-purchase-invoice-notice-send",
            code="purchase:invoice_notice:send",
            name="发送开票通知",
        ),
        Permission(
            id="perm-purchase-followup-view",
            code="purchase:followup:view",
            name="查看采购跟单",
        ),
        Permission(
            id="perm-followup-template-view",
            code="followup:template:view",
            name="查看跟单模板",
        ),
        Permission(
            id="perm-followup-template-edit",
            code="followup:template:edit",
            name="维护跟单模板",
        ),
        Permission(
            id="perm-followup-plan-view",
            code="followup:plan:view",
            name="查看采购跟单计划",
        ),
        Permission(
            id="perm-followup-plan-edit",
            code="followup:plan:edit",
            name="维护采购跟单计划",
        ),
        Permission(
            id="perm-followup-plan-view-all",
            code="followup:plan:view_all",
            name="查看全部采购跟单计划",
        ),
        Permission(
            id="perm-quality-inspection-view",
            code="quality:inspection:view",
            name="查看 QC 查验",
        ),
        Permission(
            id="perm-quality-inspection-edit",
            code="quality:inspection:edit",
            name="维护 QC 查验",
        ),
        Permission(
            id="perm-quality-inspection-view-all",
            code="quality:inspection:view_all",
            name="查看全部 QC 查验",
        ),
        Permission(
            id="perm-warehouse-inbound-plan-view",
            code="warehouse:inbound_plan:view",
            name="查看入库计划",
        ),
        Permission(
            id="perm-warehouse-inbound-plan-edit",
            code="warehouse:inbound_plan:edit",
            name="维护入库计划",
        ),
        Permission(
            id="perm-warehouse-inbound-plan-view-all",
            code="warehouse:inbound_plan:view_all",
            name="查看全部入库计划",
        ),
        Permission(
            id="perm-warehouse-inbound-order-view",
            code="warehouse:inbound_order:view",
            name="查看货物入库",
        ),
        Permission(
            id="perm-warehouse-inbound-order-edit",
            code="warehouse:inbound_order:edit",
            name="维护货物入库",
        ),
        Permission(
            id="perm-warehouse-inbound-order-approve",
            code="warehouse:inbound_order:approve",
            name="审批货物入库",
        ),
        Permission(
            id="perm-warehouse-inbound-order-view-all",
            code="warehouse:inbound_order:view_all",
            name="查看全部货物入库",
        ),
        Permission(
            id="perm-warehouse-outbound-plan-view",
            code="warehouse:outbound_plan:view",
            name="查看出库计划",
        ),
        Permission(
            id="perm-warehouse-outbound-plan-edit",
            code="warehouse:outbound_plan:edit",
            name="维护出库计划",
        ),
        Permission(
            id="perm-warehouse-outbound-plan-view-all",
            code="warehouse:outbound_plan:view_all",
            name="查看全部出库计划",
        ),
        Permission(
            id="perm-warehouse-outbound-order-view",
            code="warehouse:outbound_order:view",
            name="查看货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-edit",
            code="warehouse:outbound_order:edit",
            name="维护货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-approve",
            code="warehouse:outbound_order:approve",
            name="审批货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-view-all",
            code="warehouse:outbound_order:view_all",
            name="查看全部货物出库",
        ),
        Permission(
            id="perm-warehouse-outbound-order-allow-negative",
            code="warehouse:outbound_order:allow_negative",
            name="授权负库存出库",
        ),
        Permission(id="perm-finance-view", code="finance:view", name="查看财务管理"),
        Permission(id="perm-reporting-view", code="reporting:view", name="查看经理查询"),
    ]
    roles = [
        Role(id="role-sales-manager", name="业务主管", code="sales_manager"),
        Role(id="role-finance", name="财务", code="finance"),
    ]
    departments = [
        Department(id="dept-sales", name="业务部", parent_id=None, sort_order=10),
        Department(id="dept-finance", name="财务部", parent_id=None, sort_order=20),
    ]
    menus = [
        MenuItem(
            id="menu-dashboard",
            label="工作桌面",
            path="/",
            icon="calendar-clock",
            required_permission="dashboard:view",
            sort_order=10,
            is_active=True,
        ),
        MenuItem(
            id="menu-products",
            label="商品资料",
            path="/masterdata/products",
            icon="package",
            required_permission="masterdata:product:view",
            sort_order=15,
            is_active=True,
        ),
        MenuItem(
            id="menu-customers",
            label="客户资料",
            path="/masterdata/customers",
            icon="users",
            required_permission="masterdata:customer:view",
            sort_order=16,
            is_active=True,
        ),
        MenuItem(
            id="menu-suppliers",
            label="供应商资料",
            path="/masterdata/suppliers",
            icon="factory",
            required_permission="masterdata:supplier:view",
            sort_order=17,
            is_active=True,
        ),
        MenuItem(
            id="menu-partners",
            label="合作伙伴",
            path="/masterdata/partners",
            icon="handshake",
            required_permission="masterdata:partner:view",
            sort_order=18,
            is_active=True,
        ),
        MenuItem(
            id="menu-document-parties",
            label="单证资料",
            path="/masterdata/document-parties",
            icon="file-stack",
            required_permission="masterdata:document_party:view",
            sort_order=19,
            is_active=True,
        ),
        MenuItem(
            id="menu-sample-requests",
            label="打样管理",
            path="/sample/requests",
            icon="flask-conical",
            required_permission="sample:request:view",
            sort_order=19,
            is_active=True,
        ),
        MenuItem(
            id="menu-sample-records",
            label="样品登记",
            path="/sample/records",
            icon="images",
            required_permission="sample:record:view",
            sort_order=20,
            is_active=True,
        ),
        MenuItem(
            id="menu-sample-deliveries",
            label="寄样管理",
            path="/sample/deliveries",
            icon="send",
            required_permission="sample:delivery:view",
            sort_order=21,
            is_active=True,
        ),
        MenuItem(
            id="menu-sales-quotations",
            label="出口报价",
            path="/sales/quotations",
            icon="file-pen-line",
            required_permission="sales:quotation:view",
            sort_order=22,
            is_active=True,
        ),
        MenuItem(
            id="menu-sales-contracts",
            label="出口合同",
            path="/sales/contracts",
            icon="file-text",
            required_permission="sales:contract:view",
            sort_order=23,
            is_active=True,
        ),
        MenuItem(
            id="menu-sales-shipments",
            label="出货明细",
            path="/sales/shipments",
            icon="send",
            required_permission="sales:shipment:view",
            sort_order=24,
            is_active=True,
        ),
        MenuItem(
            id="menu-purchase-inquiries",
            label="采购询价",
            path="/purchase/inquiries",
            icon="search",
            required_permission="purchase:inquiry:view",
            sort_order=25,
            is_active=True,
        ),
        MenuItem(
            id="menu-purchase-contracts",
            label="采购合同",
            path="/purchase/contracts",
            icon="file-text",
            required_permission="purchase:contract:view",
            sort_order=26,
            is_active=True,
        ),
        MenuItem(
            id="menu-purchase-invoice-notices",
            label="开票通知",
            path="/purchase/invoice-notices",
            icon="file-pen-line",
            required_permission="purchase:invoice_notice:view",
            sort_order=27,
            is_active=True,
        ),
        MenuItem(
            id="menu-purchase-followup",
            label="采购跟单",
            path="/purchase/followup",
            icon="check-circle",
            required_permission="followup:plan:view",
            sort_order=30,
            is_active=True,
        ),
        MenuItem(
            id="menu-quality-inspections",
            label="QC 查验",
            path="/quality/inspections",
            icon="clipboard-check",
            required_permission="quality:inspection:view",
            sort_order=31,
            is_active=True,
        ),
        MenuItem(
            id="menu-warehouse-inbound-plans",
            label="入库计划",
            path="/warehouse/inbound-plans",
            icon="warehouse",
            required_permission="warehouse:inbound_plan:view",
            sort_order=32,
            is_active=True,
        ),
        MenuItem(
            id="menu-warehouse-inbound-orders",
            label="货物入库",
            path="/warehouse/inbound-orders",
            icon="warehouse",
            required_permission="warehouse:inbound_order:view",
            sort_order=33,
            is_active=True,
        ),
        MenuItem(
            id="menu-warehouse-outbound-plans",
            label="出库计划",
            path="/warehouse/outbound-plans",
            icon="send",
            required_permission="warehouse:outbound_plan:view",
            sort_order=34,
            is_active=True,
        ),
        MenuItem(
            id="menu-warehouse-outbound-orders",
            label="货物出库",
            path="/warehouse/outbound-orders",
            icon="send",
            required_permission="warehouse:outbound_order:view",
            sort_order=35,
            is_active=True,
        ),
        MenuItem(
            id="menu-finance",
            label="财务管理",
            path="/finance",
            icon="wallet",
            required_permission="finance:view",
            sort_order=40,
            is_active=True,
        ),
        MenuItem(
            id="menu-reporting",
            label="经理查询",
            path="/reporting",
            icon="bar-chart-3",
            required_permission="reporting:view",
            sort_order=45,
            is_active=True,
        ),
    ]

    existing_permission_ids = set((await session.scalars(select(Permission.id))).all())
    existing_role_ids = set((await session.scalars(select(Role.id))).all())
    existing_department_ids = set((await session.scalars(select(Department.id))).all())
    existing_menu_ids = set((await session.scalars(select(MenuItem.id))).all())
    session.add_all([item for item in permissions if item.id not in existing_permission_ids])
    session.add_all([item for item in roles if item.id not in existing_role_ids])
    session.add_all([item for item in departments if item.id not in existing_department_ids])
    session.add_all([item for item in menus if item.id not in existing_menu_ids])
    existing_menus = {
        item.id: item
        for item in (await session.scalars(select(MenuItem))).all()
    }
    for menu in menus:
        existing = existing_menus.get(menu.id)
        if existing is None:
            continue
        existing.label = menu.label
        existing.path = menu.path
        existing.icon = menu.icon
        existing.required_permission = menu.required_permission
        existing.sort_order = menu.sort_order
        existing.is_active = menu.is_active
    await session.flush()

    demo_salt = "demo-salt"
    finance_salt = "finance-salt"
    users = [
        User(
            id="u-001",
            username="demo",
            display_name="演示业务主管",
            department_id="dept-sales",
            password_hash=hash_password("demo123", demo_salt),
            password_salt=demo_salt,
            is_active=True,
            created_at=datetime.now(UTC),
        ),
        User(
            id="u-finance",
            username="finance",
            display_name="演示财务",
            department_id="dept-finance",
            password_hash=hash_password("finance123", finance_salt),
            password_salt=finance_salt,
            is_active=True,
            created_at=datetime.now(UTC),
        ),
    ]
    user_roles = [
        UserRole(id="ur-demo-sales-manager", user_id="u-001", role_id="role-sales-manager"),
        UserRole(id="ur-finance", user_id="u-finance", role_id="role-finance"),
    ]
    role_permissions = [
        RolePermission(
            id="rp-sales-dashboard",
            role_id="role-sales-manager",
            permission_id="perm-dashboard-view",
        ),
        RolePermission(
            id="rp-sales-schedule",
            role_id="role-sales-manager",
            permission_id="perm-schedule-create",
        ),
        RolePermission(
            id="rp-sales-product-view",
            role_id="role-sales-manager",
            permission_id="perm-product-view",
        ),
        RolePermission(
            id="rp-sales-product-edit",
            role_id="role-sales-manager",
            permission_id="perm-product-edit",
        ),
        RolePermission(
            id="rp-sales-product-export",
            role_id="role-sales-manager",
            permission_id="perm-product-export",
        ),
        RolePermission(
            id="rp-sales-customer-view",
            role_id="role-sales-manager",
            permission_id="perm-customer-view",
        ),
        RolePermission(
            id="rp-sales-customer-edit",
            role_id="role-sales-manager",
            permission_id="perm-customer-edit",
        ),
        RolePermission(
            id="rp-sales-customer-credit-view",
            role_id="role-sales-manager",
            permission_id="perm-customer-credit-view",
        ),
        RolePermission(
            id="rp-sales-customer-credit-edit",
            role_id="role-sales-manager",
            permission_id="perm-customer-credit-edit",
        ),
        RolePermission(
            id="rp-sales-customer-view-all",
            role_id="role-sales-manager",
            permission_id="perm-customer-view-all",
        ),
        RolePermission(
            id="rp-sales-supplier-view",
            role_id="role-sales-manager",
            permission_id="perm-supplier-view",
        ),
        RolePermission(
            id="rp-sales-supplier-edit",
            role_id="role-sales-manager",
            permission_id="perm-supplier-edit",
        ),
        RolePermission(
            id="rp-sales-supplier-credit-view",
            role_id="role-sales-manager",
            permission_id="perm-supplier-credit-view",
        ),
        RolePermission(
            id="rp-sales-supplier-credit-edit",
            role_id="role-sales-manager",
            permission_id="perm-supplier-credit-edit",
        ),
        RolePermission(
            id="rp-sales-supplier-view-all",
            role_id="role-sales-manager",
            permission_id="perm-supplier-view-all",
        ),
        RolePermission(
            id="rp-sales-partner-view",
            role_id="role-sales-manager",
            permission_id="perm-partner-view",
        ),
        RolePermission(
            id="rp-sales-partner-edit",
            role_id="role-sales-manager",
            permission_id="perm-partner-edit",
        ),
        RolePermission(
            id="rp-sales-partner-view-all",
            role_id="role-sales-manager",
            permission_id="perm-partner-view-all",
        ),
        RolePermission(
            id="rp-sales-document-party-view",
            role_id="role-sales-manager",
            permission_id="perm-document-party-view",
        ),
        RolePermission(
            id="rp-sales-document-party-edit",
            role_id="role-sales-manager",
            permission_id="perm-document-party-edit",
        ),
        RolePermission(
            id="rp-sales-document-party-view-all",
            role_id="role-sales-manager",
            permission_id="perm-document-party-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-request-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-view",
        ),
        RolePermission(
            id="rp-sales-sample-request-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-edit",
        ),
        RolePermission(
            id="rp-sales-sample-request-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-request-fee-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-fee-edit",
        ),
        RolePermission(
            id="rp-sales-sample-record-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-record-view",
        ),
        RolePermission(
            id="rp-sales-sample-record-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-record-edit",
        ),
        RolePermission(
            id="rp-sales-sample-record-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sample-record-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-view",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-edit",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-approve",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-approve",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-fee-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-fee-view",
        ),
        RolePermission(
            id="rp-sales-quotation-view",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-view",
        ),
        RolePermission(
            id="rp-sales-quotation-edit",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-edit",
        ),
        RolePermission(
            id="rp-sales-quotation-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-view-all",
        ),
        RolePermission(
            id="rp-sales-quotation-approve",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-approve",
        ),
        RolePermission(
            id="rp-sales-quotation-export",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-export",
        ),
        RolePermission(
            id="rp-sales-contract-view",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-view",
        ),
        RolePermission(
            id="rp-sales-contract-edit",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-edit",
        ),
        RolePermission(
            id="rp-sales-contract-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-view-all",
        ),
        RolePermission(
            id="rp-sales-contract-approve",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-approve",
        ),
        RolePermission(
            id="rp-sales-contract-export",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-export",
        ),
        RolePermission(
            id="rp-sales-shipment-view",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-view",
        ),
        RolePermission(
            id="rp-sales-shipment-edit",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-edit",
        ),
        RolePermission(
            id="rp-sales-shipment-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-view-all",
        ),
        RolePermission(
            id="rp-sales-shipment-approve",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-approve",
        ),
        RolePermission(
            id="rp-purchase-inquiry-view",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-view",
        ),
        RolePermission(
            id="rp-purchase-inquiry-edit",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-edit",
        ),
        RolePermission(
            id="rp-purchase-inquiry-view-all",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-view-all",
        ),
        RolePermission(
            id="rp-purchase-inquiry-export",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-export",
        ),
        RolePermission(
            id="rp-purchase-contract-view",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-view",
        ),
        RolePermission(
            id="rp-purchase-contract-edit",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-edit",
        ),
        RolePermission(
            id="rp-purchase-contract-view-all",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-view-all",
        ),
        RolePermission(
            id="rp-purchase-contract-approve",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-approve",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-view",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-view",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-edit",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-edit",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-view-all",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-view-all",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-send",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-send",
        ),
        RolePermission(
            id="rp-sales-followup",
            role_id="role-sales-manager",
            permission_id="perm-purchase-followup-view",
        ),
        RolePermission(
            id="rp-followup-template-view",
            role_id="role-sales-manager",
            permission_id="perm-followup-template-view",
        ),
        RolePermission(
            id="rp-followup-template-edit",
            role_id="role-sales-manager",
            permission_id="perm-followup-template-edit",
        ),
        RolePermission(
            id="rp-followup-plan-view",
            role_id="role-sales-manager",
            permission_id="perm-followup-plan-view",
        ),
        RolePermission(
            id="rp-followup-plan-edit",
            role_id="role-sales-manager",
            permission_id="perm-followup-plan-edit",
        ),
        RolePermission(
            id="rp-followup-plan-view-all",
            role_id="role-sales-manager",
            permission_id="perm-followup-plan-view-all",
        ),
        RolePermission(
            id="rp-quality-inspection-view",
            role_id="role-sales-manager",
            permission_id="perm-quality-inspection-view",
        ),
        RolePermission(
            id="rp-quality-inspection-edit",
            role_id="role-sales-manager",
            permission_id="perm-quality-inspection-edit",
        ),
        RolePermission(
            id="rp-quality-inspection-view-all",
            role_id="role-sales-manager",
            permission_id="perm-quality-inspection-view-all",
        ),
        RolePermission(
            id="rp-warehouse-inbound-plan-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-plan-view",
        ),
        RolePermission(
            id="rp-warehouse-inbound-plan-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-plan-edit",
        ),
        RolePermission(
            id="rp-warehouse-inbound-plan-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-plan-view-all",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-view",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-edit",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-approve",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-approve",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-view-all",
        ),
        RolePermission(
            id="rp-warehouse-outbound-plan-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-plan-view",
        ),
        RolePermission(
            id="rp-warehouse-outbound-plan-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-plan-edit",
        ),
        RolePermission(
            id="rp-warehouse-outbound-plan-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-plan-view-all",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-view",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-edit",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-approve",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-approve",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-view-all",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-allow-negative",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-allow-negative",
        ),
        RolePermission(
            id="rp-sales-reporting-view",
            role_id="role-sales-manager",
            permission_id="perm-reporting-view",
        ),
        RolePermission(
            id="rp-finance-dashboard",
            role_id="role-finance",
            permission_id="perm-dashboard-view",
        ),
        RolePermission(
            id="rp-finance-finance-view",
            role_id="role-finance",
            permission_id="perm-finance-view",
        ),
    ]
    existing_user_ids = set((await session.scalars(select(User.id))).all())
    existing_user_role_ids = set((await session.scalars(select(UserRole.id))).all())
    existing_role_permission_ids = set((await session.scalars(select(RolePermission.id))).all())
    existing_role_permission_pairs = {
        (role_id, permission_id)
        for role_id, permission_id in (
            await session.execute(
                select(RolePermission.role_id, RolePermission.permission_id)
            )
        ).all()
    }
    session.add_all([item for item in users if item.id not in existing_user_ids])
    session.add_all([item for item in user_roles if item.id not in existing_user_role_ids])
    session.add_all(
        [
            item
            for item in role_permissions
            if item.id not in existing_role_permission_ids
            and (item.role_id, item.permission_id) not in existing_role_permission_pairs
        ]
    )
    await session.commit()
