from datetime import UTC, datetime

from app.modules.system.auth.models import RolePermission, User, UserRole
from app.modules.system.auth.passwords import hash_password


def demo_users() -> list[User]:
    admin_salt = "admin-salt"
    demo_salt = "demo-salt"
    finance_salt = "finance-salt"
    return [
        User(
            id="u-admin",
            username="admin",
            display_name="演示管理员",
            department_id=None,
            avatar_type="preset",
            avatar_value="ink-halo",
            password_hash=hash_password("admin123", admin_salt),
            password_salt=admin_salt,
            is_active=True,
            created_at=datetime.now(UTC),
        ),
        User(
            id="u-001",
            username="demo",
            display_name="演示业务主管",
            department_id=None,
            avatar_type="preset",
            avatar_value="amber-orbit",
            password_hash=hash_password("demo123", demo_salt),
            password_salt=demo_salt,
            is_active=True,
            created_at=datetime.now(UTC),
        ),
        User(
            id="u-finance",
            username="finance",
            display_name="演示财务",
            department_id=None,
            avatar_type="preset",
            avatar_value="sage-pulse",
            password_hash=hash_password("finance123", finance_salt),
            password_salt=finance_salt,
            is_active=True,
            created_at=datetime.now(UTC),
        ),
    ]


def demo_user_roles() -> list[UserRole]:
    return [
        UserRole(id="ur-admin", user_id="u-admin", role_id="role-admin"),
        UserRole(id="ur-demo-sales-manager", user_id="u-001", role_id="role-sales-manager"),
        UserRole(id="ur-finance", user_id="u-finance", role_id="role-finance"),
    ]


def demo_role_permissions() -> list[RolePermission]:
    return [
        RolePermission(
            id="rp-admin-dashboard",
            role_id="role-admin",
            permission_id="perm-dashboard-view",
        ),
        RolePermission(
            id="rp-admin-super-admin",
            role_id="role-admin",
            permission_id="perm-system-super-admin",
        ),
        RolePermission(
            id="rp-admin-announcement-create",
            role_id="role-admin",
            permission_id="perm-announcement-create",
        ),
        RolePermission(
            id="rp-admin-organization-user-manage",
            role_id="role-admin",
            permission_id="perm-organization-user-manage",
        ),
        RolePermission(
            id="rp-sales-dashboard",
            role_id="role-sales-manager",
            permission_id="perm-dashboard-view",
        ),
        RolePermission(
            id="rp-sales-schedule",
            role_id="role-sales-manager",
            permission_id="perm-schedule-create",
        ),
        RolePermission(
            id="rp-sales-product-view",
            role_id="role-sales-manager",
            permission_id="perm-product-view",
        ),
        RolePermission(
            id="rp-sales-product-edit",
            role_id="role-sales-manager",
            permission_id="perm-product-edit",
        ),
        RolePermission(
            id="rp-sales-product-export",
            role_id="role-sales-manager",
            permission_id="perm-product-export",
        ),
        RolePermission(
            id="rp-sales-customer-view",
            role_id="role-sales-manager",
            permission_id="perm-customer-view",
        ),
        RolePermission(
            id="rp-sales-customer-edit",
            role_id="role-sales-manager",
            permission_id="perm-customer-edit",
        ),
        RolePermission(
            id="rp-sales-customer-credit-view",
            role_id="role-sales-manager",
            permission_id="perm-customer-credit-view",
        ),
        RolePermission(
            id="rp-sales-customer-credit-edit",
            role_id="role-sales-manager",
            permission_id="perm-customer-credit-edit",
        ),
        RolePermission(
            id="rp-sales-customer-view-all",
            role_id="role-sales-manager",
            permission_id="perm-customer-view-all",
        ),
        RolePermission(
            id="rp-sales-supplier-view",
            role_id="role-sales-manager",
            permission_id="perm-supplier-view",
        ),
        RolePermission(
            id="rp-sales-supplier-edit",
            role_id="role-sales-manager",
            permission_id="perm-supplier-edit",
        ),
        RolePermission(
            id="rp-sales-supplier-credit-view",
            role_id="role-sales-manager",
            permission_id="perm-supplier-credit-view",
        ),
        RolePermission(
            id="rp-sales-supplier-credit-edit",
            role_id="role-sales-manager",
            permission_id="perm-supplier-credit-edit",
        ),
        RolePermission(
            id="rp-sales-supplier-view-all",
            role_id="role-sales-manager",
            permission_id="perm-supplier-view-all",
        ),
        RolePermission(
            id="rp-sales-partner-view",
            role_id="role-sales-manager",
            permission_id="perm-partner-view",
        ),
        RolePermission(
            id="rp-sales-partner-edit",
            role_id="role-sales-manager",
            permission_id="perm-partner-edit",
        ),
        RolePermission(
            id="rp-sales-partner-view-all",
            role_id="role-sales-manager",
            permission_id="perm-partner-view-all",
        ),
        RolePermission(
            id="rp-sales-document-party-view",
            role_id="role-sales-manager",
            permission_id="perm-document-party-view",
        ),
        RolePermission(
            id="rp-sales-document-party-edit",
            role_id="role-sales-manager",
            permission_id="perm-document-party-edit",
        ),
        RolePermission(
            id="rp-sales-document-party-view-all",
            role_id="role-sales-manager",
            permission_id="perm-document-party-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-request-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-view",
        ),
        RolePermission(
            id="rp-sales-sample-request-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-edit",
        ),
        RolePermission(
            id="rp-sales-sample-request-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-request-fee-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-request-fee-edit",
        ),
        RolePermission(
            id="rp-sales-sample-record-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-record-view",
        ),
        RolePermission(
            id="rp-sales-sample-record-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-record-edit",
        ),
        RolePermission(
            id="rp-sales-sample-record-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sample-record-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-view",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-edit",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-edit",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-view-all",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-approve",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-approve",
        ),
        RolePermission(
            id="rp-sales-sample-delivery-fee-view",
            role_id="role-sales-manager",
            permission_id="perm-sample-delivery-fee-view",
        ),
        RolePermission(
            id="rp-sales-quotation-view",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-view",
        ),
        RolePermission(
            id="rp-sales-quotation-edit",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-edit",
        ),
        RolePermission(
            id="rp-sales-quotation-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-view-all",
        ),
        RolePermission(
            id="rp-sales-quotation-approve",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-approve",
        ),
        RolePermission(
            id="rp-sales-quotation-export",
            role_id="role-sales-manager",
            permission_id="perm-sales-quotation-export",
        ),
        RolePermission(
            id="rp-sales-contract-view",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-view",
        ),
        RolePermission(
            id="rp-sales-contract-edit",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-edit",
        ),
        RolePermission(
            id="rp-sales-contract-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-view-all",
        ),
        RolePermission(
            id="rp-sales-contract-approve",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-approve",
        ),
        RolePermission(
            id="rp-sales-contract-export",
            role_id="role-sales-manager",
            permission_id="perm-sales-contract-export",
        ),
        RolePermission(
            id="rp-sales-shipment-view",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-view",
        ),
        RolePermission(
            id="rp-sales-shipment-edit",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-edit",
        ),
        RolePermission(
            id="rp-sales-shipment-view-all",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-view-all",
        ),
        RolePermission(
            id="rp-sales-shipment-approve",
            role_id="role-sales-manager",
            permission_id="perm-sales-shipment-approve",
        ),
        RolePermission(
            id="rp-purchase-inquiry-view",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-view",
        ),
        RolePermission(
            id="rp-purchase-inquiry-edit",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-edit",
        ),
        RolePermission(
            id="rp-purchase-inquiry-view-all",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-view-all",
        ),
        RolePermission(
            id="rp-purchase-inquiry-export",
            role_id="role-sales-manager",
            permission_id="perm-purchase-inquiry-export",
        ),
        RolePermission(
            id="rp-purchase-contract-view",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-view",
        ),
        RolePermission(
            id="rp-purchase-contract-edit",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-edit",
        ),
        RolePermission(
            id="rp-purchase-contract-view-all",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-view-all",
        ),
        RolePermission(
            id="rp-purchase-contract-approve",
            role_id="role-sales-manager",
            permission_id="perm-purchase-contract-approve",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-view",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-view",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-edit",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-edit",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-view-all",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-view-all",
        ),
        RolePermission(
            id="rp-purchase-invoice-notice-send",
            role_id="role-sales-manager",
            permission_id="perm-purchase-invoice-notice-send",
        ),
        RolePermission(
            id="rp-sales-followup",
            role_id="role-sales-manager",
            permission_id="perm-purchase-followup-view",
        ),
        RolePermission(
            id="rp-followup-template-view",
            role_id="role-sales-manager",
            permission_id="perm-followup-template-view",
        ),
        RolePermission(
            id="rp-followup-template-edit",
            role_id="role-sales-manager",
            permission_id="perm-followup-template-edit",
        ),
        RolePermission(
            id="rp-followup-plan-view",
            role_id="role-sales-manager",
            permission_id="perm-followup-plan-view",
        ),
        RolePermission(
            id="rp-followup-plan-edit",
            role_id="role-sales-manager",
            permission_id="perm-followup-plan-edit",
        ),
        RolePermission(
            id="rp-followup-plan-view-all",
            role_id="role-sales-manager",
            permission_id="perm-followup-plan-view-all",
        ),
        RolePermission(
            id="rp-quality-inspection-view",
            role_id="role-sales-manager",
            permission_id="perm-quality-inspection-view",
        ),
        RolePermission(
            id="rp-quality-inspection-edit",
            role_id="role-sales-manager",
            permission_id="perm-quality-inspection-edit",
        ),
        RolePermission(
            id="rp-quality-inspection-view-all",
            role_id="role-sales-manager",
            permission_id="perm-quality-inspection-view-all",
        ),
        RolePermission(
            id="rp-warehouse-inbound-plan-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-plan-view",
        ),
        RolePermission(
            id="rp-warehouse-inbound-plan-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-plan-edit",
        ),
        RolePermission(
            id="rp-warehouse-inbound-plan-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-plan-view-all",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-view",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-edit",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-approve",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-approve",
        ),
        RolePermission(
            id="rp-warehouse-inbound-order-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-inbound-order-view-all",
        ),
        RolePermission(
            id="rp-warehouse-outbound-plan-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-plan-view",
        ),
        RolePermission(
            id="rp-warehouse-outbound-plan-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-plan-edit",
        ),
        RolePermission(
            id="rp-warehouse-outbound-plan-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-plan-view-all",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-view",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-view",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-edit",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-edit",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-approve",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-approve",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-view-all",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-view-all",
        ),
        RolePermission(
            id="rp-warehouse-outbound-order-allow-negative",
            role_id="role-sales-manager",
            permission_id="perm-warehouse-outbound-order-allow-negative",
        ),
        RolePermission(
            id="rp-sales-reporting-view",
            role_id="role-sales-manager",
            permission_id="perm-reporting-view",
        ),
        RolePermission(
            id="rp-finance-dashboard",
            role_id="role-finance",
            permission_id="perm-dashboard-view",
        ),
        RolePermission(
            id="rp-finance-finance-view",
            role_id="role-finance",
            permission_id="perm-finance-view",
        ),
    ]
